@api = http://localhost:3000/task

GET {{api}}

###

GET {{api}}/1

###

GET {{api}}/count

### 

POST  {{api}}
Content-Type: application/json

{
    "title": "task 7",
    "description": "Somer descriptions task seven"
}

###

DELETE {{api}}/5


###

PUT {{api}}/1
Content-Type: application/json

{
    "title": "task one"
}
